### ISSUE TITLE
Shorten the cache job

### ISSUE THREAD

**Issue by mthrok** [pytorch/text#1237]
Currently the cache job detects if the cache exists by retrieving the cache. This adds 5 mins to all the unit tests and GBs of data transferred but not used. We should stop retrieving the cache in cache generation jobs.

Unfortunately CCI does not provide a mechanism to check if a cache exists.

A workaround is to cache a small file, which is easy to fetch, alongside of the actual cache, then restore only this small file.
If the small file exists, nothing needs to be done otherwise, the job can generate cache. 

```
restore_cache:
  key: foobar
  paths:
    - small_file
cache_generation:
  command:
    <generate cache only when small_file does not exist>
save_cache:  # if the small_file existed in `restore_cache` stage, this has no effect
  key: foobar
  paths:
    - small_file
    - the real cache
```

cc @parmeet
